### ISSUE TITLE
complete staging-beta deployment

### ISSUE THREAD

**Issue by eauge** [oasislabs/oasis-gateway#73]
- [x] Putting secrets to chamber (private_key). We will just generate another one.
- [x] Enable https (right now it only listens with http). Needs some work in the component
- [x] Use redis instance
- [x] Automatic funding of a private key on redeployment (https://github.com/oasislabs/developer-gateway/issues/79)
- [x] Readiness and liveness probes
- [x] What should we do with the logs?
